### ISSUE TITLE
How to set Canvas from the Kameleo API?

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-typescript#10]
What would be the proper code syntax form to set the Canvas from the Kameleo API?

Also, could your provide some example code?

**Comment by KameleoStaff** [comment]
We recently released Kameleo v4.0.0, which introduced several changes and improvements to the platform. As a result, this code has been updated to be fully compatible with the latest version.

```
@type {import('@kameleo/local-api-client').CreateProfileRequest} */
const createProfileRequest = {
  fingerprintId: fingerprints[0].id,
  canvas: 'intelligent' // Options: 'intelligent', 'noise', 'block', 'off'
};

const profile = await client.profile.createProfile(createProfileRequest);
```

These answers are provided from the Kameleo [Set Canvas from API](https://help.kameleo.io/hc/en-us/articles/13602501279772-Set-Canvas-from-API) article.
