### ISSUE TITLE
How to set WebRTC from the Kameleo API?

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-typescript#14]
What would be the proper code syntax form to set the WebRTC for a profile from the Kameleo API?

Also, could your provide some example code?

**Comment by MBailey01** [comment]
Here is an example that you can use to set the WebRTC for a profile through the API:

```
const createProfileRequest = BuilderForCreateProfile
    .forBaseProfile(baseProfileId)
    .setWebRtc('manual', { 
        privateIp: '192.168.1.1', 
        publicIp: '123.456.78.90' 
    })
    .build();
const profile = await client.createProfile({ body: createProfileRequest });
```

These answers are provided from the Kameleo [Set WebRTC from API](https://help.kameleo.io/hc/en-us/articles/14990482761372-Set-WebRTC-from-API) article.

**Comment by deaktomi** [comment]
I think `webrtc.privateIP` is removed from the API in 4.0.0. Please update the code and also update the article. 
[See for reference](https://app.swaggerhub.com/apis/kameleo-team/kameleo-local-api/4.0.0#/WebRtcSpoofingOptions)
