### ISSUE TITLE
How to set Names and Tags from the Kameleo API?

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-typescript#18]
What would be the proper code syntax form to set the Name and Tags for a profile from the Kameleo API?

Also, could your provide some example code?

**Comment by MBailey01** [comment]
Here is an example that you can use to set the Name and Tags for a profile through the API:

- **Name**:
```
const createProfileRequest = BuilderForCreateProfile
  .forBaseProfile(chromeBaseProfileList[0].id)
  .setRecommendedDefaults()
  .setName('ScrapingProfile1')
  .build();
const profile = await client.createProfile({ body: createProfileRequest });
```

- **Tags**:
```
const createProfileRequest = BuilderForCreateProfile
  .forBaseProfile(chromeBaseProfileList[0].id)
  .setRecommendedDefaults()
  .setTags(['scraping', 'automation'])
  .build();
const profile = await client.createProfile({ body: createProfileRequest });
```

These answers are provided from the Kameleo [Set Names and Tags from API](https://help.kameleo.io/hc/en-us/articles/15082784889244-Set-Names-and-Tags-from-API) article.
