### ISSUE TITLE
Migrate off `@azure/ms-rest-js`

### ISSUE THREAD

**Issue by jeremymeng** [kameleo-io/local-api-client-typescript#3]
It looks that old version of autorest typescript generator was used to generate code that depends on `@azure/ms-rest-js`?

Please consider moving to use latest autorest.typescript code generator as `@azure/ms-rest-js` is no longer actively maintained.  Free free to reach out if you have any questions.

**Comment by kameleo-team** [comment]
Hello @jeremymeng , 
we already updated the python libary, please check. We will also do with the C# and javascript soon

**Comment by jeremymeng** [comment]
@kameleo-team This is for javascript I think.

**Comment by jeremymeng** [comment]
yeah looks good now. thanks!
