### ISSUE TITLE
Changing proxy inside profile causes error

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-typescript#4]
Upon trying to change a proxy inside profile we get this error:

```
let  profile=await kameleoClient.readProfile(gm_kameleo_profile);

      //console.log(profile);
      profile.proxy= {
          value: 'http',
          extra: {
            host: proxy_ip,
            port: parseInt(proxy_port),
          }};
   

         // console.log(profile);
     await kameleoClient.updateProfile(gm_kameleo_profile, {
              body: profile,
      });


```
At line:1 char:1
+ node .\winxxxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\ytscan\node_...t\index.js:1321:String) [], RemoteExce
   ption
    + FullyQualifiedErrorId : NativeCommandError
 
    const error = new coreRestPipeline.RestError(initialErrorMessage, {
                  ^
RestError: {"code":400,"error":{"hardwareConcurrency":["The HardwareConcurrency field is required."]}}
    at handleErrorResponse (C:\ytscan\node_modules\@azure\core-client\dist\index.js:1321:19)
    at deserializeResponseBody (C:\ytscan\node_modules\@azure\core-client\dist\index.js:1256:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: undefined,

**Comment by MBailey01** [comment]
By checking the issue with the hardware concurrency field missing, please make sure you update to the latest NPM package. Here is the table for compatibility: https://help.kameleo.io/hc/en-us/articles/4418391839249-Kameleo-Local-API-Client#heading-4

The new version of NPM (v3.1) is available for Kameleo v3.1. This can be seen on the Kameleo Local API article here > https://help.kameleo.io/hc/en-us/articles/4418391839249-Kameleo-Local-API-Client#h_01HP72KFHTD24GCPQ7H3TZEKAA
