### ISSUE TITLE
How to run scraper code on Linux while Kameleo is running on Windows

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-typescript#5]
I'd like to know whether it's possible to run Kameleo.CLI on a Windows machine and to launch Playwright instances on a Linux machine using Javascript?

**Comment by MBailey01** [comment]
There is a guide that explains this thoroughly, it can be viewed by accessing https://help.kameleo.io/hc/en-us/articles/13400684344476-Run-scraper-code-on-Linux-while-Kameleo-is-running-on-Windows

It consists of the following:

1. Configuring the Kameleo.CLI by opening port 5050. 
2. Updating the client configuration by either using Python code, in this case:

`const kameleoPort = 5050;
const client = new KameleoLocalApiClient({
  baseUri: `http://IP_OF_WINDOWS_MACHINE:${kameleoPort}`,
  noRetryPolicy: true,
});`

3. Launching Playwright instances on Linux using the following code:

`const browserWSEndpoint = `ws://IP_OF_WINDOWS_MACHINE:${kameleoPort}/playwright/${profile.id}`;
`
