### ISSUE TITLE
Last tab still opens on profile start

### ISSUE THREAD

**Issue by MBailey01** [kameleo-io/local-api-client-typescript#6]
Hello,

I had a question about starting profiles, whether there is a way to open a new tab instead of loading up the previously saved session? Furthermore, if there is a way to do it, can be be done with in a manner where cookies persist across sessions?

Thank you!

**Comment by JonathanR25** [comment]
To prevent your browser from opening tabs from previous sessions, you can configure the profile settings to always start with a specific page. This can be done in a couple of simple steps:

1.Access Profile Settings:

 - Click on the three dots "..." next to your profile.
 - Select "Edit" from the dropdown menu.

2.Navigate to Advanced Settings:

 - Once in the profile settings, click on "Advanced Settings"
 - Switch to the "Browser" tab.

3.Set the Start Page:

 - In the "Start Page" section, input the URL you want to be displayed
   when you open the profile.
 - To start with a blank page, simply type about:newtab.or about:blank.

Furthermore, you can also make these changes via the CLI by using the following code:

For JavaScript:
```
const createProfileRequest = BuilderForCreateProfile 
   .set_start_page('about:newtab') \
```
This information is also available on one of the public articles that Kameleo has -> https://help.kameleo.io/hc/en-us/articles/14190549346588-Reopen-profiles-with-empty-page
